	<!-- Header -->
	<div id="headertop">
		<div class="wrapper-login">
			<!-- Title/Logo - can use text instead of image -->
			<div id="title"><?php echo $this->company_name; ?>指令平台<!--<span>Administry</span> demo--></div>
			<!-- Aside links -->
			<!--<aside><b>English</b> &middot; <a href="#">Spanish</a> &middot; <a href="#">German</a></aside>-->
			<!-- End of Aside links -->
		</div>
	</div>
	<!-- End of Header -->
	<!-- Page title -->
	<div id="pagetitle">
		<div class="wrapper-login"></div>
	</div>
	<!-- End of Page title -->
	
	<!-- Page content -->
	<div id="page">
		<!-- Wrapper -->
		<div class="wrapper-login">
				<!-- Login form -->
				<section class="full">					
					
					<h3>&nbsp;</h3>
					
					<div class="box box-info">请输入用户名和密码登录系统</div>

					<form id="loginform" method="post" action="/index/login">

						<p>
							<label for="username">用户名:</label><br/>
							<input type="text" id="username" class="full" value="" name="username"/>
						</p>
						
						<p>
							<label for="password">密码:</label><br/>
							<input type="password" id="password" class="full" value="" name="password"/>
						</p>
						
						<!--
						<p>
							<input type="checkbox" id="remember" class="" value="1" name="remember"/>
							<label class="choice" for="remember">Remember me?</label>
						</p>
						-->
						
						<p>
							<input type="submit" class="btn btn-green big" value="登录"/> &nbsp; 
							<!--<a href="javascript: //;" onClick="$('#emailform').slideDown(); return false;">Forgot password?</a> or <a href="#">Need help?</a>-->
						</p>
						<div class="clear">&nbsp;</div>
						<div class="clear">&nbsp;</div>
						<div class="clear">&nbsp;</div>
						<div class="clear">&nbsp;</div>
						<div class="clear">&nbsp;</div>
						<div class="clear">&nbsp;</div>
						<div class="clear">&nbsp;</div>
						<div class="clear">&nbsp;</div>
						<div class="clear">&nbsp;</div>
						<div class="clear">&nbsp;</div>

					</form>
					
					<form id="emailform" style="display:none" method="post" action="#">
						<div class="box">
							<p id="emailinput">
								<label for="email">Email:</label><br/>
								<input type="text" id="email" class="full" value="" name="email"/>
							</p>
							<p>
								<input type="submit" class="btn" value="Send"/>
							</p>
						</div>
					</form>
					
				</section>
				<!-- End of login form -->
				
		</div>
		<!-- End of Wrapper -->
	</div>
	<!-- End of Page content -->
	
	<!-- Page footer -->
	<footer id="bottom">
		<div class="wrapper-login">
			<p>Copyright &copy; 2011 <b><?php echo $this->company_name; ?></b></p>
		</div>
	</footer>
	<!-- End of Page footer -->

<!-- User interface javascript load -->
<!--<script type="text/javascript" SRC="js/administry.js"></script>-->